[package]
authors = ["Ceri Storey <ceri@lshift.net>"]
name = "upgraded-spork"
version = "0.1.0"

[dependencies]
backtrace = "*"
env_logger = "0.3.5"
futures = "0.1.1"
log = "0.3.6"

[dependencies.tokio-service]
git = "https://github.com/tokio-rs/tokio-service"
optional = false
